version: 2.1
jobs:
  python27:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - run: python run.py deps
      - run: python run.py ci-driver
  python39:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - run: python run.py deps
      - run: python3 run.py ci-driver
workflows:
  version: 2
  arm64:
    jobs:
      - python27
      - python39
