version: 2.1
jobs:
  python27:
    docker:
      - image: cimg/python:2.7
    resource_class: arm.medium
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y python-setuptools
      - run: python run.py deps
      - run: python run.py ci-driver
  python39:
    docker:
      - image: cimg/python:3.9
    resource_class: arm.medium
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y python3-setuptools
      - run: python run.py deps
      - run: python3 run.py ci-driver
workflows:
  version: 2
  arm64:
    jobs:
      - python27
      - python39
