name: CI
on: [push, pull_request]

jobs:
  build-windows:
    name: Python ${{ matrix.python }} on windows-2022 ${{ matrix.arch }}
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.11'
          # - 'pypy-3.7-v7.3.5'
        arch:
          - 'x86'
          - 'x64'
        exclude:
          - python: 'pypy-3.7-v7.3.5'
            arch: x86
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.arch }}
      - name: Install dependencies
        run: python run.py deps
      - name: Run test suite
        run: python run.py ci-driver
      - name: Run test suite (Windows legacy API)
        run: python run.py ci-driver winlegacy

  build-windows-old:
    name: Python ${{ matrix.python }} on windows-2022 ${{ matrix.arch }}
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        python:
          - '2.6'
          - '2.7'
          - '3.3'
        arch:
          - 'x86'
          - 'x64'
    steps:
      - uses: actions/checkout@master

      - name: Cache Python
        id: cache-python
        uses: actions/cache@v4
        with:
          path: ~/AppData/Local/Python${{ matrix.python }}-${{ matrix.arch }}
          key: windows-2019-python-${{ matrix.python }}-${{ matrix.arch }}

      - name: Install Python ${{ matrix.python }}
        run: python run.py python-install ${{ matrix.python }} ${{ matrix.arch }} | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install dependencies
        run: python run.py deps
      - name: Run test suite
        run: python run.py ci-driver
      - name: Run test suite (Windows legacy API)
        run: python run.py ci-driver winlegacy

  build-mac:
    name: Python ${{ matrix.python }} on macos-14
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.11'
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install dependencies
        run: python run.py deps
      - name: Run test suite
        run: python run.py ci-driver
      - name: Run test suite (Mac cffi)
        run: python run.py ci-driver cffi
      - name: Run test suite (Mac OpenSSL)
        run: python run.py ci-driver openssl
      - name: Run test suite (Mac OpenSSL/cffi)
        run: python run.py ci-driver cffi openssl

  build-ubuntu-openssl3-py3:
    name: Python 3 on (Docker) ubuntu-22.04 x64
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - uses: actions/checkout@master
      - name: Install Python and OpenSSL
        run: dev/ubuntu.sh py3
      - name: Install dependencies
        run: python run.py deps
      - name: Run test suite
        run: python run.py ci-driver
      - name: Run test suite (cffi)
        run: python run.py ci-driver cffi

  build-ubuntu-openssl3-py2:
    name: Python 2 on (Docker) ubuntu-22.04 x64
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - uses: actions/checkout@master
      - name: Install Python and OpenSSL
        run: dev/ubuntu.sh py2
      - name: Install dependencies
        run: python2 run.py deps
      - name: Run test suite
        run: python2 run.py ci-driver
      - name: Run test suite (cffi)
        run: python2 run.py ci-driver cffi
